// <auto-generated />
namespace dpaw_alerts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeparktable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeparktable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300423288_change-park-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
